name: "Cosmovisor"

on:
  workflow_dispatch:
    inputs:
      tag:
        description: The docker tag for the publish
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      # Docker login
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PUSH_TOKEN }}
      # Build and push docker image
      - name: Build docker image
        uses: docker/build-push-action@v4
        with:
          file: tools/cosmovisor/Dockerfile
          push: true
          tags: |
            peersyst/exrp-cosmovisor:${{ github.event.inputs.tag }}
            peersyst/exrp-cosmovisor:latest
