name: Release
on:
  workflow_dispatch:
    inputs:
      commit_branch:
        description: The branch or the commit sha to push tag to
        required: true
      tag:
        description: The tag of the release
        required: true
      is_latest_release:
        description: Is this the latest release
        type: boolean
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.commit_branch }}
      - run:
          TAG=${{ github.event.inputs.tag }}
          echo "VERSION=${TAG#v}" >> $GITHUB_ENV
      - name: Issue Release Assets 
        uses: ignite/cli/actions/cli@v0.27.2
        with:
          args: chain build --release --release.prefix exrp_${{ env.VERSION }} -t linux:amd64 -t darwin:amd64 -t darwin:arm64 -y
      - name: Check prerelease
        id: check-prerelease
        run: |
          if [[ ${{ github.event.inputs.tag }} =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo "match=true" >> $GITHUB_OUTPUT
          fi
      - name: Publish the Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.tag }}
          files: release/*
          prerelease: steps.check-prerelease.outputs.match == 'true'
          target_commitish: ${{ github.event.inputs.commit_branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
