name: Release
on:
  workflow_dispatch:
    inputs:
      commit_branch:
        description: The branch or the commit sha to push tag to
        required: true
      tag:
        description: The tag of the release
        required: true
      is_latest_release:
        description: Is this the latest release
        type: boolean
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.commit_branch }}
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      # Docker login
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PUSH_TOKEN }}
      # Build and push docker image
      - name: Build docker image
        uses: docker/build-push-action@v4
        with:
          target: release
          push: true
          build-args: VERSION=${{ github.event.inputs.tag }}
          tags: |
            peersyst/exrp:${{ github.event.inputs.tag }}
            ${{ fromJSON('["", "peersyst/exrp:latest"]')[github.event.inputs.is_latest_release == 'true'] }}
      - name: Extract release binaries from docker image
        run: |
          docker run --rm -v $PWD/release:/release peersyst/exrp:${{ github.event.inputs.tag }} "cp /binaries/* /release"
      - name: Publish the Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.tag }}
          files: release/*
          prerelease: steps.check-prerelease.outputs.match == 'true'
          target_commitish: ${{ github.event.inputs.commit_branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
